// Currency Chaos — Master Currency Database
// Real currencies use live rates fetched from API
// Fictional currencies: canonical rates where confirmed, hypothesized otherwise

const CURRENCIES = [
  // ── REAL CURRENCIES ─────────────────────────────────────────────────────────
  { code:"USD",  name:"US Dollar",          symbol:"$",   flag:"🇺🇸", category:"real",  usdRate:1,          realCurrency:true,  flavorText:"The world's reserve currency. Also the reason everyone else has anxiety." },
  { code:"EUR",  name:"Euro",               symbol:"€",   flag:"🇪🇺", category:"real",  usdRate:null,       realCurrency:true,  flavorText:"Used in 20 countries, argued about in all 27." },
  { code:"GBP",  name:"British Pound",      symbol:"£",   flag:"🇬🇧", category:"real",  usdRate:null,       realCurrency:true,  flavorText:"Survived Napoleon, two world wars, and Brexit. Still standing. Barely." },
  { code:"JPY",  name:"Japanese Yen",       symbol:"¥",   flag:"🇯🇵", category:"real",  usdRate:null,       realCurrency:true,  flavorText:"When you need 1,000 of something to buy a coffee, the denominations get exciting." },
  { code:"CHF",  name:"Swiss Franc",        symbol:"Fr",  flag:"🇨🇭", category:"real",  usdRate:null,       realCurrency:true,  flavorText:"Stable, precise, and suspiciously well-hidden in Alpine vaults. Sebastian approves." },
  { code:"CNY",  name:"Chinese Yuan",       symbol:"¥",   flag:"🇨🇳", category:"real",  usdRate:null,       realCurrency:true,  flavorText:"Powers the world's factory. And probably your phone too." },
  { code:"CAD",  name:"Canadian Dollar",    symbol:"C$",  flag:"🇨🇦", category:"real",  usdRate:null,       realCurrency:true,  flavorText:"The polite dollar. Even the beaver on it looks apologetic." },
  { code:"AUD",  name:"Australian Dollar",  symbol:"A$",  flag:"🇦🇺", category:"real",  usdRate:null,       realCurrency:true,  flavorText:"Comes with a complimentary kangaroo encounter. Currency not responsible for injuries." },
  { code:"INR",  name:"Indian Rupee",       symbol:"₹",   flag:"🇮🇳", category:"real",  usdRate:null,       realCurrency:true,  flavorText:"Powers 1.4 billion people and Bollywood's entire VFX budget." },
  { code:"KRW",  name:"South Korean Won",   symbol:"₩",   flag:"🇰🇷", category:"real",  usdRate:null,       realCurrency:true,  flavorText:"The currency of K-pop, fried chicken, and surprisingly powerful semiconductors." },
  { code:"BRL",  name:"Brazilian Real",     symbol:"R$",  flag:"🇧🇷", category:"real",  usdRate:null,       realCurrency:true,  flavorText:"Named 'Real' to signal it was finally a real currency. Bold move. Mostly works." },
  { code:"MXN",  name:"Mexican Peso",       symbol:"$",   flag:"🇲🇽", category:"real",  usdRate:null,       realCurrency:true,  flavorText:"Has survived more currency crises than your average action movie hero." },
  { code:"SEK",  name:"Swedish Krona",      symbol:"kr",  flag:"🇸🇪", category:"real",  usdRate:null,       realCurrency:true,  flavorText:"Sweden is nearly cashless. The Krona exists mostly to confuse tourists." },
  { code:"NOK",  name:"Norwegian Krone",    symbol:"kr",  flag:"🇳🇴", category:"real",  usdRate:null,       realCurrency:true,  flavorText:"Backed by North Sea oil. Also fjords. Mostly oil." },
  { code:"SGD",  name:"Singapore Dollar",   symbol:"S$",  flag:"🇸🇬", category:"real",  usdRate:null,       realCurrency:true,  flavorText:"One of the world's most stable currencies. Also the city-state fines you for chewing gum." },
  { code:"NZD",  name:"New Zealand Dollar", symbol:"NZ$", flag:"🇳🇿", category:"real",  usdRate:null,       realCurrency:true,  flavorText:"Technically the Hobbit dollar. Tolkien just didn't know it yet." },
  { code:"ZAR",  name:"South African Rand", symbol:"R",   flag:"🇿🇦", category:"real",  usdRate:null,       realCurrency:true,  flavorText:"The Rand. Because 'we had to call it something' was already taken." },
  { code:"RUB",  name:"Russian Ruble",      symbol:"₽",   flag:"🇷🇺", category:"real",  usdRate:null,       realCurrency:true,  flavorText:"Has more rollercoaster moments than an actual rollercoaster. Gravity optional." },
  { code:"TRY",  name:"Turkish Lira",       symbol:"₺",   flag:"🇹🇷", category:"real",  usdRate:null,       realCurrency:true,  flavorText:"Currently in a dramatic relationship with inflation. It's very complicated." },

  // ── CRYPTO (Top 50 by market cap — live via CoinGecko) ──────────────────────
  { code:"BTC",   name:"Bitcoin",            symbol:"₿",   flag:"🟠", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"bitcoin",           flavorText:"Invented by a ghost, powered by electricity, and somehow worth more than your house." },
  { code:"ETH",   name:"Ethereum",           symbol:"Ξ",   flag:"⬡",  category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"ethereum",          flavorText:"Like Bitcoin but with more features and more ways to lose all your money." },
  { code:"USDT",  name:"Tether",             symbol:"₮",   flag:"💵", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"tether",            flavorText:"It's a dollar. On the blockchain. For when regular dollars feel too stable." },
  { code:"XRP",   name:"XRP",                symbol:"X",   flag:"🔵", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"ripple",            flavorText:"The crypto lawyers have fought about this longer than most marriages last." },
  { code:"BNB",   name:"BNB",                symbol:"B",   flag:"🟡", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"binancecoin",       flavorText:"Binance's native token. Buy it or pay more fees. The most honest loyalty program in finance." },
  { code:"SOL",   name:"Solana",             symbol:"S",   flag:"🟣", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"solana",            flavorText:"Fast, cheap, and occasionally offline. Like a sports car that sometimes won't start." },
  { code:"USDC",  name:"USD Coin",           symbol:"$",   flag:"🔵", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"usd-coin",          flavorText:"Another dollar on the blockchain. Backed by actual dollars, unlike some we know." },
  { code:"DOGE",  name:"Dogecoin",           symbol:"D",   flag:"🐕", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"dogecoin",          flavorText:"Started as a joke. Then Elon tweeted. Now we're all just here living in it." },
  { code:"ADA",   name:"Cardano",            symbol:"A",   flag:"🔵", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"cardano",           flavorText:"Peer-reviewed academic crypto. Still waiting for full deployment. The thesis is almost done." },
  { code:"TRX",   name:"TRON",               symbol:"T",   flag:"🔴", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"tron",              flavorText:"Ambitious plans, questionable copyright history, relentless momentum. TRON plays itself." },
  { code:"AVAX",  name:"Avalanche",          symbol:"A",   flag:"🔴", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"avalanche-2",       flavorText:"Consensus reached in under a second. Unfortunately investors disagree on the price." },
  { code:"SHIB",  name:"Shiba Inu",          symbol:"S",   flag:"🐶", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"shiba-inu",         flavorText:"DOGE for people who thought DOGE was too respectable. An entire ecosystem built on vibes." },
  { code:"TON",   name:"Toncoin",            symbol:"T",   flag:"💎", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"the-open-network",  flavorText:"Built by Telegram. Banned by the SEC. Unbanned. Still going. Resilient, like a chat message." },
  { code:"DOT",   name:"Polkadot",           symbol:".",   flag:"⚫", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"polkadot",          flavorText:"The blockchain that connects blockchains. A blockchain of blockchains. Chainsception." },
  { code:"LINK",  name:"Chainlink",          symbol:"L",   flag:"🔵", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"chainlink",         flavorText:"The bridge between blockchain and real-world data. Possibly the most useful thing here." },
  { code:"BCH",   name:"Bitcoin Cash",       symbol:"B",   flag:"🟢", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"bitcoin-cash",      flavorText:"Bitcoin but bigger blocks. The great 2017 schism produced this. Now there are two Bitcoins and twice the arguments." },
  { code:"XLM",   name:"Stellar",            symbol:"*",   flag:"⭐", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"stellar",           flavorText:"Designed for sending money across borders cheaply. Nobel Prize economists consulted. Still $0.13." },
  { code:"UNI",   name:"Uniswap",            symbol:"U",   flag:"🦄", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"uniswap",           flavorText:"A unicorn that lets you swap tokens. If you understand what that means, congratulations." },
  { code:"LTC",   name:"Litecoin",           symbol:"L",   flag:"⚪", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"litecoin",          flavorText:"The silver to Bitcoin's gold. Exists mostly to make Bitcoin feel prestigious by comparison." },
  { code:"NEAR",  name:"NEAR Protocol",      symbol:"N",   flag:"🌐", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"near",              flavorText:"Human-readable addresses on blockchain. Because 0x4F2b... wasn't great for business cards." },
  { code:"ICP",   name:"Internet Computer",  symbol:"I",   flag:"♾️", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"internet-computer", flavorText:"A blockchain that wants to replace the internet. Bold claim. Checking back in 10 years." },
  { code:"APT",   name:"Aptos",              symbol:"A",   flag:"🔷", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"aptos",             flavorText:"Ex-Meta engineers built a blockchain. The Zuckerverse collapsed so they went decentralized." },
  { code:"ETC",   name:"Ethereum Classic",   symbol:"E",   flag:"🟢", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"ethereum-classic",  flavorText:"The original Ethereum that refused to roll back a hack. Purists only. Hardcore vibes." },
  { code:"STX",   name:"Stacks",             symbol:"S",   flag:"🟠", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"blockstack",        flavorText:"Bitcoin's programmable layer. Because someone decided Bitcoin needed apps and wasn't wrong." },
  { code:"CRO",   name:"Cronos",             symbol:"C",   flag:"🔵", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"crypto-com-chain",  flavorText:"Spent $700M on a stadium name deal. The arena was renamed. The token survived. Resilience." },
  { code:"FIL",   name:"Filecoin",           symbol:"F",   flag:"🌿", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"filecoin",          flavorText:"Pay people to store your files on their spare hard drives. Airbnb but for your data and nightmares." },
  { code:"HBAR",  name:"Hedera",             symbol:"H",   flag:"🔷", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"hedera-hashgraph",  flavorText:"Not actually a blockchain — it's a hashgraph. That's technically different. Lawyers are involved." },
  { code:"VET",   name:"VeChain",            symbol:"V",   flag:"🌱", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"vechain",           flavorText:"Supply chain tracking on the blockchain. LVMH uses it. Your counterfeit handbag does not." },
  { code:"MNT",   name:"Mantle",             symbol:"M",   flag:"⚫", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"mantle",            flavorText:"An Ethereum Layer 2 with treasury billions. The boring kind of crypto. Which is the good kind." },
  { code:"ALGO",  name:"Algorand",           symbol:"A",   flag:"⚫", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"algorand",          flavorText:"Turing Award winner founded this blockchain. It is fast. It is elegant. The price is, however, less elegant." },
  { code:"OP",    name:"Optimism",           symbol:"O",   flag:"🔴", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"optimism",          flavorText:"Ethereum but faster and cheaper via rollups. Named 'Optimism' because someone had to be." },
  { code:"ARB",   name:"Arbitrum",           symbol:"A",   flag:"🔵", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"arbitrum",          flavorText:"Another Ethereum scaler. The optimistic rollup wars are somehow more civil than the blockchain ones." },
  { code:"ATOM",  name:"Cosmos",             symbol:"A",   flag:"🌌", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"cosmos",            flavorText:"The Internet of Blockchains. All blockchains talking to each other. What could go wrong." },
  { code:"GRT",   name:"The Graph",          symbol:"G",   flag:"🟣", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"the-graph",         flavorText:"Google for blockchain data. The blockchain needed a search engine. Here it is." },
  { code:"INJ",   name:"Injective",          symbol:"I",   flag:"🔵", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"injective-protocol",flavorText:"Decentralized derivatives trading. Finance bros found the blockchain. Nothing was ever the same." },
  { code:"MKR",   name:"Maker",              symbol:"M",   flag:"🟢", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"maker",             flavorText:"Governs the DAI stablecoin. One MKR buys you a vote and a sense of responsibility for a $10B system." },
  { code:"THETA", name:"Theta Network",      symbol:"0",   flag:"🎬", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"theta-token",       flavorText:"Decentralized video streaming. YouTube but everyone is the CDN. Samsung invested. Sure." },
  { code:"FLOW",  name:"Flow",               symbol:"F",   flag:"🌊", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"flow",              flavorText:"NBA Top Shot lives here. Dapper Labs built it for NFT sports highlights. Then NFTs happened." },
  { code:"FTM",   name:"Fantom",             symbol:"F",   flag:"👻", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"fantom",            flavorText:"Fast and cheap. Once had a famous chef-turned-defi-pioneer. The chef left. The chain stayed." },
  { code:"EGLD",  name:"MultiversX",         symbol:"E",   flag:"🌐", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"elrond-erd-2",      flavorText:"Formerly Elrond, now MultiversX. Rebranded into the metaverse like every company in 2021." },
  { code:"XMR",   name:"Monero",             symbol:"M",   flag:"🔒", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"monero",            flavorText:"The privacy coin. Untraceable by design. Beloved by the genuinely concerned and the genuinely suspicious." },
  { code:"IMX",   name:"Immutable X",        symbol:"I",   flag:"🎮", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"immutable-x",       flavorText:"NFT gaming layer on Ethereum. Zero gas fees for game items. The gamers came. Some stayed." },
  { code:"SAND",  name:"The Sandbox",        symbol:"S",   flag:"🏖️", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"the-sandbox",       flavorText:"Virtual land that sold for millions. Snoop Dogg has a plot. The metaverse hype was real for 15 minutes." },
  { code:"MANA",  name:"Decentraland",       symbol:"M",   flag:"🌐", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"decentraland",      flavorText:"Virtual real estate on a blockchain. Someone paid $2.4M for a plot. The concurrent user count is lower than your local arcade." },
  { code:"AAVE",  name:"Aave",               symbol:"A",   flag:"👻", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"aave",              flavorText:"Borrow crypto with crypto as collateral. Banking re-invented, now in a ghost costume." },
  { code:"AXS",   name:"Axie Infinity",      symbol:"A",   flag:"🐾", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"axie-infinity",     flavorText:"Play-to-earn gaming at its peak. Filipino families made a living from it. Then the economy collapsed. Then it recovered. The scholarship program was unprecedented in gaming history." },
  { code:"RUNE",  name:"THORChain",          symbol:"R",   flag:"⚡", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"thorchain",         flavorText:"Cross-chain swaps without wrapped tokens. Named after Norse runes. Odin would have questions about the smart contracts." },
  { code:"KCS",   name:"KuCoin Token",       symbol:"K",   flag:"🟢", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"kucoin-shares",     flavorText:"KuCoin exchange's own token. Gives you discounts. The exchange got hacked for $280M and kept operating. Resilience is on brand." },
  { code:"CFX",   name:"Conflux",            symbol:"C",   flag:"🌀", category:"real", usdRate:null, realCurrency:true, isCrypto:true, geckoId:"conflux-token",     flavorText:"The only SEC-compliant Chinese blockchain, apparently. A very specific niche. They own it." },

  // ── GAMES ────────────────────────────────────────────────────────────────────
  // Skyrim — hypothesized ~$0.25 (sweet roll = 2 Septims ≈ $0.50)
  { code:"SEP",  name:"Septim",             symbol:"⚜",   flag:"🏰",  category:"games", usdRate:0.25,       realCurrency:false, universe:"The Elder Scrolls / Skyrim",    canonical:false, flavorText:"A gold coin of Tamriel. A sweet roll costs 2 Septims; a house with a murderer costs 8,000. Skyrim pricing is a national emergency." },
  // Final Fantasy Gil — ~$0.01 (Big Mac index puts $1 ≈ 220 Gil)
  { code:"GIL",  name:"Gil",                symbol:"G",   flag:"🌀",  category:"games", usdRate:0.01,       realCurrency:false, universe:"Final Fantasy",                 canonical:false, flavorText:"Dropped by monsters, found in treasure chests in ancient ruins. Cloud saved the planet and spent the proceeds on a sword shaped like a door." },
  // Fallout — ~$0.23 (9mm HP round = 3 caps ≈ $0.69 in real life)
  { code:"CAP",  name:"Bottle Cap",         symbol:"¢",   flag:"☢️",  category:"games", usdRate:0.23,       realCurrency:false, universe:"Fallout",                       canonical:false, flavorText:"After nuclear war, humanity replaced money with Nuka-Cola caps. This is, genuinely, more thoughtful monetary policy than several real governments have managed." },
  // Minecraft — ~$8 (Game Theory analysis via labor equivalence)
  { code:"EMR",  name:"Emerald",            symbol:"◆",   flag:"⬛",  category:"games", usdRate:8.0,        realCurrency:false, universe:"Minecraft",                     canonical:false, flavorText:"A single Emerald can buy 1 piece of bread OR an enchanted weapon. Villager economic models are peer-reviewed by nobody." },
  // Animal Crossing — canonical: Nintendo Switch costs identical in Bells and Yen
  { code:"BELL", name:"Bell",               symbol:"🔔",  flag:"🌿",  category:"games", usdRate:0.0065,     realCurrency:false, universe:"Animal Crossing",               canonical:true,  flavorText:"Nintendo confirmed Bells = Yen. Tom Nook offers mortgages with zero interest and no deadlines. He is objectively a better banker than any real institution. He is a raccoon." },
  // WoW Gold — canonical: WoW Token ~288,860 gold = $20 USD
  { code:"GOLD", name:"WoW Gold",           symbol:"G",   flag:"🐉",  category:"games", usdRate:0.0000344,  realCurrency:false, universe:"World of Warcraft",             canonical:true,  flavorText:"Has a real-world regulated exchange rate via the Token system. Azerothian economists have written real papers about auction house manipulation. Academics weep." },
  // One Piece Beli — canonical: Shueisha Mugiwara Store uses ¥1 = ฿1
  { code:"BELI", name:"Beli",               symbol:"฿",   flag:"🏴‍☠️", category:"games", usdRate:0.0065,     realCurrency:false, universe:"One Piece",                     canonical:true,  flavorText:"Luffy's bounty grew from 30M to 3B Beli based entirely on how many important people he punched. Inflation in the New World is personal." },
  // Naruto Ryō — canonical: Narutopedia states 1 Ryō = 10 Yen
  { code:"RYO",  name:"Ryō",               symbol:"両",   flag:"🍃",  category:"games", usdRate:0.065,      realCurrency:false, universe:"Naruto",                        canonical:true,  flavorText:"An S-rank mission pays 1,000,000 Ryō (~$65,000). Kakashi has 248 A-rank missions completed and still can't afford a haircut. Where is the money going, sensei?" },
  // Dragon Ball Zeni — canonical: Toriyama stated 1 Zeni = 1 Yen
  { code:"ZENI", name:"Zeni",              symbol:"Z",   flag:"💥",  category:"games", usdRate:0.0065,     realCurrency:false, universe:"Dragon Ball",                   canonical:true,  flavorText:"Officially 1 Zeni = 1 Yen, per Akira Toriyama, who also later said 1.5 Yen, because Toriyama was famously cavalier about continuity. Frieza genocided planets for real estate contracts." },
  // Genshin Mora — ~$0.0038 (onion costs 80 Mora vs. $0.29 real)
  { code:"MORA", name:"Mora",              symbol:"◈",   flag:"💫",  category:"games", usdRate:0.0038,     realCurrency:false, universe:"Genshin Impact",                canonical:false, flavorText:"Backed by a god who retired to become a funeral director. Every character upgrade costs 420,000 Mora. You have 80 characters. You will never be done. Please send help." },
  // Zelda Rupees — ~$0.14 (Tears of the Kingdom: apple = 12 Rupees vs. $1.74 real)
  { code:"RUPI", name:"Rupee",             symbol:"◈",   flag:"💎",  category:"games", usdRate:0.14,       realCurrency:false, universe:"The Legend of Zelda",            canonical:false, flavorText:"Come in Green (1), Blue (5), Red (20), Purple (50), Silver (100), Gold (300). Found by cutting grass. Link has saved the world 17 times and still can't afford a house without side quests." },
  // Sims Simoleon — ~$0.31 (coffee analysis: 5 Simoleons vs. $1.89 IRL)
  { code:"SIMOL",name:"Simoleon",          symbol:"§",   flag:"🏠",  category:"games", usdRate:0.31,       realCurrency:false, universe:"The Sims",                      canonical:false, flavorText:"The game starts you with §20,000 ($6,200 USD). You immediately spend §4,500 on a hot tub. No roof. The cheat code 'motherlode' adds $15,500. Economists call this the hot tub paradox." },
  // Stardew Gold — ~$0.027 (crop price analysis: 37 gold = $1)
  { code:"SSTAR",name:"Gold (Stardew)",    symbol:"g",   flag:"🌾",  category:"games", usdRate:0.027,      realCurrency:false, universe:"Stardew Valley",                canonical:false, flavorText:"Pierre's shop is closed on Wednesdays. Nobody knows why. Nobody asks. You have 2,000 jars of Ancient Fruit Wine worth $125 each. Pierre doesn't deserve you." },
  // Pokédollar — canonical: The Pokémon Company confirmed = Yen
  { code:"POK",  name:"Pokédollar",        symbol:"₽",   flag:"⚡",  category:"games", usdRate:0.0065,     realCurrency:false, universe:"Pokémon",                       canonical:true,  flavorText:"Officially just the Yen in a trenchcoat. A Pokéball costs 200₽ (~$1.30), which is a reasonable price to compress a living creature into a sphere. Parenting in Kanto starts at age 10 with no map." },
  // Fortnite V-Bucks — canonical: 1000 V-Bucks = $7.99
  { code:"VBUCK",name:"V-Buck",            symbol:"V",   flag:"🎮",  category:"games", usdRate:0.008,      realCurrency:false, universe:"Fortnite",                      canonical:true,  flavorText:"The Fishstick skin cost $15. This is a fish. In a suit. Fortnite has contributed more to behavioral economics than any university program. The skin is called Fishstick." },
  // Roblox Robux — canonical: 80 Robux = $1
  { code:"ROBUX",name:"Robux",             symbol:"R$",  flag:"🟥",  category:"games", usdRate:0.0125,     realCurrency:false, universe:"Roblox",                        canonical:true,  flavorText:"Developers aged 14 have made six-figure real incomes. Items cost odd Robux amounts so you always have leftover. You will buy a hat that makes your avatar look like a shrimp." },
  // D&D Gold Piece — ~$100 (labor-based: 1 SP = half day's labor at $63/4hr)
  { code:"RPGOLD",name:"Gold Piece",       symbol:"GP",  flag:"🎲",  category:"games", usdRate:100.0,      realCurrency:false, universe:"Dungeons & Dragons",            canonical:false, flavorText:"Worth ~$100 USD. A Healing Potion (50 GP) costs $5,000 — highway robbery for what is essentially a magical energy drink. Every party treasurer has had a breakdown over D&D economics." },
  // RuneScape — Jagex Bonds: 12.3M GP = $6, so 1 GP ≈ $0.00000049
  { code:"RUNEG",name:"RuneScape GP",      symbol:"gp",  flag:"⚔️",  category:"games", usdRate:0.00000049, realCurrency:false, universe:"RuneScape",                     canonical:false, flavorText:"OSRS gold briefly became MORE valuable than the Venezuelan Bolívar. Not a joke. The Grand Exchange operates more efficiently than most real stock markets. Jagex shut down the casino because it caused real gambling addiction." },
  // League of Legends RP — canonical: 575 RP = $4.99
  { code:"LORPK", name:"Riot Points (RP)", symbol:"RP",  flag:"🏆",  category:"games", usdRate:0.0087,     realCurrency:false, universe:"League of Legends",             canonical:true,  flavorText:"The most expensive skin runs $100+ worth of RP. Faker doesn't buy skins. He doesn't need to. He IS the skin." },
  // GTA — Shark Cards: $5 = $250,000 GTA$
  { code:"GTA",  name:"GTA Dollar",        symbol:"$",   flag:"🚔",  category:"games", usdRate:0.00003,    realCurrency:false, universe:"Grand Theft Auto Online",       canonical:false, flavorText:"A fighter jet costs $150 real money. You will be blown up by a 12-year-old in an orbital cannon within 30 minutes. The economy exists to sell Shark Cards. This is by design." },
  // Dark Souls — ~$0.01 (shortsword = 1,000 Souls ≈ $10 basic weapon)
  { code:"SOUL", name:"Soul",              symbol:"☯",   flag:"👻",  category:"games", usdRate:0.01,       realCurrency:false, universe:"Dark Souls / Elden Ring",       canonical:false, flavorText:"The literal spiritual essence of everything you've killed. Drop them on death, retrieve them once, or they're gone forever. This is called 'inventory management.' You died falling off the ledge trying to get them back." },
  // Resident Evil Pesetas — canonical: 100 Pts = 0.60 EUR, Spain 2004
  { code:"PTAS", name:"Peseta",            symbol:"Pts", flag:"🧟",  category:"games", usdRate:0.0072,     realCurrency:false, universe:"Resident Evil 4",               canonical:true,  flavorText:"The actual defunct Spanish Peseta. RE4 takes place in rural Spain in 2004, two years after Spain switched to Euros. The Los Illuminados cult never updated their POS systems. Leon collects them from corpses. No questions asked." },
  // Borderlands Eridium — ~$3 (in-game: excess Eridium = $3,000 game money, correlated)
  { code:"ERID", name:"Eridium",           symbol:"E",   flag:"🟣",  category:"games", usdRate:3.0,        realCurrency:false, universe:"Borderlands",                   canonical:false, flavorText:"Ancient alien power source that appeared after the Vault opened. First application: extra grenade storage. An alien relic that could rewrite physics and you spent it on backpack space." },
  // LEGO Studs — ~$0.0001 (millions per level, in-game scale)
  { code:"STUD", name:"Stud",              symbol:"●",   flag:"🧱",  category:"games", usdRate:0.0001,     realCurrency:false, universe:"LEGO Video Games",              canonical:false, flavorText:"Every LEGO game — Batman, Indiana Jones, Darth Vader — uses Studs. The 'True Stud Finder' cheat multiplies studs by 3,840×. No economist called it hyperinflation. They called it 'fun.'" },
  // Destiny Glimmer — ~$0.001 (freighter = 1B Units ≈ scale reference)
  { code:"GLMR", name:"Glimmer",           symbol:"✦",   flag:"🌌",  category:"games", usdRate:0.001,      realCurrency:false, universe:"Destiny 2",                     canonical:false, flavorText:"Crystallized Light — the congealed residue of the universe's most powerful energy — used to buy ammunition. Glimmer is capped at 250,000 so nobody can hoard it. Accidentally the most egalitarian economy in gaming." },
  // Cyberpunk Eddies — ~$0.25 (lore: $2 USD = 1 Eurodollar at conversion)
  { code:"EDDY", name:"Eurodollar (Eddies)",symbol:"€$", flag:"🤖",  category:"games", usdRate:0.25,       realCurrency:false, universe:"Cyberpunk 2077",                canonical:false, flavorText:"The currency of a capitalist hellhole where poverty is illegal. A quickhack that explodes someone's neural implant costs 45,000 Eddies. V starts the game broke and ends it either rich and dying, or just dying." },
  // Metro MGR — ~$5 (real 5.45×39mm ≈ $0.50, post-nuclear scarcity premium)
  { code:"MGR",  name:"Military-Grade Round",symbol:"MGR",flag:"☣️", category:"games", usdRate:5.0,        realCurrency:false, universe:"Metro 2033 / Last Light",        canonical:false, flavorText:"Post-nuclear Russia chose pre-war ammunition as currency. It can't be counterfeited without machinery, everyone has guns, and you can always shoot it at a mutant instead. The most honest expression of opportunity cost in any video game." },
  // Undertale GOLD — ~$0.28 (Tough Glove 50G ≈ $15 real fingerless glove)
  { code:"UGOLD",name:"GOLD (Undertale)",   symbol:"G",   flag:"💛",  category:"games", usdRate:0.28,       realCurrency:false, universe:"Undertale",                     canonical:false, flavorText:"Temmie uses your GOLD to fund her college education. Sans sells hot dogs out of a trenchcoat pocket. You earn GOLD from enemies you chose not to kill. It's bought with mercy. That actually makes it the best currency on this list." },
  // Shadowrun Nuyen — ~$0.10 (bread = 2 Nuyen vs. $0.20, pistol = 450 Nuyen vs. $45)
  { code:"NUYEN",name:"Nuyen",              symbol:"¥",   flag:"🐉",  category:"games", usdRate:0.10,       realCurrency:false, universe:"Shadowrun",                     canonical:false, flavorText:"The currency of a world where dragons sit on corporate boards and you can be an elf hacker with a troll street samurai. The corps own everything. The runners take their cut from the cracks. Hoi, chummer." },
  // EVE ISK — canonical via PLEX: 1.5B ISK ≈ $19.99
  { code:"ISK",  name:"ISK (EVE Online)",   symbol:"ISK", flag:"🚀",  category:"games", usdRate:0.0000000133,realCurrency:false,universe:"EVE Online",                    canonical:false, flavorText:"CCP Games employs a real economist. The Great War of 2014 destroyed the equivalent of $330,000 USD in virtual ships. Banking fraud committed entirely inside the game has collapsed real alliances. EVE Online is not a game. It is a civilization." },
  // BioShock ADAM — ~$50 (scarce genetic mutagen, produced by sea slugs)
  { code:"ADAM", name:"ADAM",               symbol:"A",   flag:"💉",  category:"games", usdRate:50.0,       realCurrency:false, universe:"BioShock",                      canonical:false, flavorText:"Produced by sea slugs colonizing human corpses, harvested from little girls, fuels the entire economy of an underwater objectivist city that is currently on fire. Would you kindly reconsider your economic model?" },
  // Mass Effect Credits — ~$1 (Medi-Gel 50cr, equipment thousands, roughly 1:1 USD)
  { code:"CRED3",name:"Credits (Mass Effect)",symbol:"CR",flag:"🚀",  category:"games", usdRate:1.0,        realCurrency:false, universe:"Mass Effect",                   canonical:false, flavorText:"Shepard saved the galaxy from the Reapers for approximately zero Credits. Meanwhile, Spectre gear costs 1,000,000 Credits. The Quarian fleet uses tech and favors. This is either admirable post-scarcity thinking or just how poor people cope." },

  // ── TV & FILM ─────────────────────────────────────────────────────────────────
  // Star Trek Latinum — fan estimate: 1 Bar ≈ $1,587 (Gizmodo 2008 analysis)
  { code:"LATM", name:"Gold-Pressed Latinum",symbol:"GPL",flag:"🖖",  category:"tv",    usdRate:1587.0,     realCurrency:false, universe:"Star Trek (Ferengi)",            canonical:false, flavorText:"The only substance in the universe that can't be replicated. The gold casing is worthless — it's the liquid latinum inside that matters. The Federation doesn't use money at all, which the Ferengi consider a mental illness." },
  { code:"CRED", name:"Federation Credit",   symbol:"CR", flag:"🖖",  category:"tv",    usdRate:2.58,       realCurrency:false, universe:"Star Trek (Federation)",         canonical:false, flavorText:"The Federation technically doesn't need money. Credits keep appearing whenever the script needs someone bribed. Schrödinger's currency: simultaneously existing and not existing. Picard describes this as 'fascinating' while sipping Earl Grey." },
  // Star Wars Credits — ~$1 (EU treats roughly 1:1 with USD for everyday items)
  { code:"GCRED",name:"Galactic Credit",     symbol:"₠",  flag:"🚀",  category:"tv",    usdRate:1.0,        realCurrency:false, universe:"Star Wars",                     canonical:false, flavorText:"'Republic credits are no good out here!' — Watto, making a macroeconomic point about Outer Rim currency sovereignty. Han Solo charged 17,000 credits to fly to Alderaan. Then Alderaan blew up. Terrible outcome. Great pilot." },
  // Game of Thrones Gold Dragon — ~$300 (3 horses = 3 Dragons, horse ≈ $300)
  { code:"DRAG", name:"Gold Dragon",         symbol:"🐉", flag:"⚔️",  category:"tv",    usdRate:300.0,      realCurrency:false, universe:"Game of Thrones / ASOIAF",      canonical:false, flavorText:"The Iron Throne's debt to the Iron Bank was 6,000,000 Gold Dragons — roughly $1.8 billion. The Iron Bank will find you if you default. The Iron Bank always finds you." },
  { code:"STAG", name:"Silver Stag",         symbol:"🦌", flag:"⚔️",  category:"tv",    usdRate:1.43,       realCurrency:false, universe:"Game of Thrones / ASOIAF",      canonical:false, flavorText:"1/210th of a Gold Dragon. The smallfolk receive their wages in these. Ned Stark didn't want the job. He got paid in Silver Stags and then got his head removed. Correlation unclear." },
  // Futurama — treated ~1:1 with 1990s USD (show written in 1999)
  { code:"FUTBK",name:"Future Dollar",       symbol:"$",  flag:"🤖",  category:"tv",    usdRate:1.0,        realCurrency:false, universe:"Futurama (year 3000)",           canonical:false, flavorText:"Fry's 93-cent bank account compounded into $4.3 billion over 1,000 years. He spent it on anchovies. The economic lesson here is either 'compound interest' or 'don't be Fry.' Possibly both." },
  // BSG Cubits — ~$2 (contextual: drinks and card games in show)
  { code:"CUBIT",name:"Cubit",               symbol:"cb", flag:"🛸",  category:"tv",    usdRate:2.0,        realCurrency:false, universe:"Battlestar Galactica",           canonical:false, flavorText:"Rectangular gold coins of the Twelve Colonies. The Cylon apocalypse killed 99.9% of the population. Survivors aboard Galactica still gamble with Cubits. Either deeply human or deeply insane. Possibly both." },
  // Cowboy Bebop Woolong — ~$0.006 (1 Woolong ≈ 1 Yen based on ramen price)
  { code:"WLNG", name:"Woolong",             symbol:"W$", flag:"🎸",  category:"tv",    usdRate:0.006,      realCurrency:false, universe:"Cowboy Bebop",                  canonical:false, flavorText:"The Bebop crew is perpetually broke. Spike is one of the most dangerous fighters alive and frequently cannot afford lunch. The bounty on the main villain was never paid. The Woolong economy of 2071 is the gig economy with spaceships." },
  // The Office Schrute Bucks — officially stated as worth NOTHING
  { code:"SCHB", name:"Schrute Buck",        symbol:"SB", flag:"🌱",  category:"tv",    usdRate:0.0001,     realCurrency:false, universe:"The Office",                    canonical:false, flavorText:"'What is a Schrute Buck?' 'It's a certificate of bravery.' Value: officially zero. 1,000 Schrute Bucks = 1 Stanley Nickel. The Stanley Nickel is worth nothing. The most honest currency ever invented." },
  { code:"STANN",name:"Stanley Nickel",      symbol:"SN", flag:"☕",  category:"tv",    usdRate:0.1,        realCurrency:false, universe:"The Office",                    canonical:false, flavorText:"'What is the ratio of Stanley Nickels to Schrute Bucks?' 'The same as the ratio of unicorns to leprechauns.' Value: one man's quiet dignity in a difficult workplace. Market cap: immeasurable." },
  // Silver Eagles (BioShock Infinite) — ~$1 (1912 Columbia, prices ≈ 1912 USD)
  { code:"SEAGL",name:"Silver Eagle",        symbol:"SE", flag:"🦅",  category:"tv",    usdRate:1.0,        realCurrency:false, universe:"BioShock Infinite",             canonical:false, flavorText:"Currency of Columbia, the city in the clouds, which runs on Silver Eagles and bad ideology. A hot dog costs 1 Silver Eagle. The gift shop is still open while a quantum tear is destroying the boardwalk. Priorities." },
  { code:"BARK", name:"Hollywoo Dollar",     symbol:"H$", flag:"🐴",  category:"tv",    usdRate:0.98,       realCurrency:false, universe:"BoJack Horseman",               canonical:false, flavorText:"The currency of Hollywoo (the D was stolen). Slightly less than a real dollar because everything in Hollywoo is slightly less than what it used to be. The show already made you feel this way." },

  // ── BOOKS & LITERATURE ───────────────────────────────────────────────────────
  // Harry Potter — canonical: J.K. Rowling 2001 Comic Relief: 1 Galleon = £5 ≈ $6.64
  { code:"GAL",  name:"Galleon",            symbol:"ʛ",  flag:"⚗️",  category:"books", usdRate:6.64,       realCurrency:false, universe:"Harry Potter",                  canonical:true,  flavorText:"J.K. Rowling confirmed 1 Galleon ≈ £5 in 2001. That means Hogwarts tuition — never mentioned in canon — is suspiciously affordable, and a Butterbeer at 2 Sickles is 78 cents. The wizarding economy is almost reasonable." },
  // Harry Potter Sickle — canonical: 17 Sickles = 1 Galleon
  { code:"SICK", name:"Sickle",            symbol:"ʂ",  flag:"⚗️",  category:"books", usdRate:0.39,       realCurrency:false, universe:"Harry Potter",                  canonical:true,  flavorText:"17 Sickles = 1 Galleon. The wizarding monetary system was designed by a drunk goblin who has since been promoted. The Sickle is reliable, underappreciated, and always in your pocket: the Ron Weasley of currency." },
  // Harry Potter Knut — canonical: 29 Knuts = 1 Sickle → $0.013
  { code:"KNUT", name:"Knut",              symbol:"ꝁ",  flag:"⚗️",  category:"books", usdRate:0.013,      realCurrency:false, universe:"Harry Potter",                  canonical:true,  flavorText:"The Daily Prophet costs 2 Knuts, which tells you everything about wizarding journalism. Neville Longbottom once found one in his shoe and considered it a good omen. He was not wrong." },
  // Witcher Crown — ~$0.35 (chicken costs ~5 Crowns, hypothesized)
  { code:"CROW", name:"Crown",             symbol:"cr", flag:"🐺",  category:"books", usdRate:0.35,       realCurrency:false, universe:"The Witcher",                   canonical:false, flavorText:"'Toss a coin to your Witcher' — the song everyone sings, but nobody does. Geralt slew an entire necromancer army and got tossed one coin. One. Not even a Crown. A merchant charges 400 Crowns for a sword guard. Something is wrong." },
  // Witcher Floren — 1 Floren = 3 Crowns at Vivaldi Bank
  { code:"FLOR", name:"Floren",            symbol:"fl", flag:"🐺",  category:"books", usdRate:1.05,       realCurrency:false, universe:"The Witcher (Nilfgaard)",        canonical:false, flavorText:"Worth three times a Crown, because the Nilfgaardian Empire's subtle way of saying 'we own you now.' You can only exchange them at Vivaldi Bank, which is realistic and also extremely annoying during a war." },
  // Witcher Oren — 1:1 with Crown at Vivaldi Bank
  { code:"OREN", name:"Oren",              symbol:"or", flag:"🐺",  category:"books", usdRate:0.35,       realCurrency:false, universe:"The Witcher",                   canonical:false, flavorText:"Old Temerian coins you find on corpses, worth exactly as much as Crowns. They're basically antiques Vivaldi Bank exchanges 1:1, which is either economic generosity or an accounting error nobody wants to flag." },
  // LotR Mithril — a single mithril shirt is worth more than the Shire
  { code:"MITH", name:"Mithril Coin",      symbol:"M",  flag:"💍",  category:"books", usdRate:4200.0,     realCurrency:false, universe:"Lord of the Rings",             canonical:false, flavorText:"A single mithril shirt is worth more than the entire Shire. Bilbo wore one. Casual. The Eagles could have flown Frodo to Mordor from the start and saved the entire economic cost of the War of the Ring but nobody asked them." },
  // Discworld AM$ — ~$0.28 (fan analysis of in-world goods)
  { code:"DOLAR",name:"Ankh-Morpork Dollar",symbol:"AM$",flag:"🐢",  category:"books", usdRate:0.28,       realCurrency:false, universe:"Discworld (Terry Pratchett)",    canonical:false, flavorText:"Backed by 'not asking too many questions.' The Thieves' Guild guarantees your wallet's safety. They guarantee it so thoroughly that they are the ones who might steal it. The Assassins' Guild has a sliding fee scale." },
  // Dune Credits — ~$1.20 (Spacing Guild monopoly on FTL, spice scarcity)
  { code:"CRED2",name:"Credit (Dune)",     symbol:"₵",  flag:"🏜️",  category:"books", usdRate:1.20,       realCurrency:false, universe:"Dune",                          canonical:false, flavorText:"Backed by the Spacing Guild's monopoly on faster-than-light travel. Also spice. Mostly spice. He who controls the spice controls the universe. He who controls the universe presumably has excellent monetary policy." },
  // Foundation Sol — ~$0.88 (Galactic Empire: 12,000 year inflation, slow)
  { code:"SOLA", name:"Sol (Foundation)",  symbol:"☀",  flag:"📖",  category:"books", usdRate:0.88,       realCurrency:false, universe:"Foundation (Asimov)",           canonical:false, flavorText:"The Galactic Empire's currency, slowly inflating over 12,000 years, exactly as Hari Seldon's Psychohistory predicted. Trantor: 40 billion people, no agriculture, entirely dependent on food imports. Also, somehow, a financial hub." },
  // Wheel of Time Mark — ~$0.12 (medieval fantasy, 8-12 Marks per silver penny comparison)
  { code:"MARK", name:"Mark",              symbol:"✦",  flag:"⚔️",  category:"books", usdRate:0.12,       realCurrency:false, universe:"Wheel of Time",                 canonical:false, flavorText:"Used across Randland's many nations, making international trade both complex and irritating. Also the name of several characters in the books, which consistently confuses new readers and is frankly Jordanesque." },
  // Hitchhiker's Guide Altairian Dollar — fans: 1 AltD = 3 pints Janx Spirit
  { code:"ALTD", name:"Altairian Dollar",  symbol:"α$", flag:"🌌",  category:"books", usdRate:3.14159,    realCurrency:false, universe:"Hitchhiker's Guide to the Galaxy",canonical:false,flavorText:"Buys exactly 3 pints of Ol' Janx Spirit. The answer to the exchange rate is 42. The question remains unknown. Also: the Vogons are responsible for the galactic financial system, which explains a great deal." },

  // ── ANIME ────────────────────────────────────────────────────────────────────
  // HxH Jenny — ~$0.0067 (Viz: 134 Jenny = $1 USD in 2006 translation)
  { code:"JENNY",name:"Jenny",             symbol:"J",  flag:"👊",  category:"anime", usdRate:0.0067,     realCurrency:false, universe:"Hunter × Hunter",               canonical:false, flavorText:"Killua had a silver credit card as a child assassin. The Zoldyck family is worth trillions. Gon can't afford training equipment. The HxH economy is just real capitalism with better fight choreography." },
  // AoT Eldian Mark — no canon name, ~$0.25 hypothesized
  { code:"WINGK",name:"Eldian Mark",       symbol:"M",  flag:"⚔️",  category:"anime", usdRate:0.25,       realCurrency:false, universe:"Attack on Titan",               canonical:false, flavorText:"When a 60-meter Titan is about to eat your city, nobody stops to check the exchange rate. The currency is shown so rarely that fans had to name it based on the show's Germanic aesthetics. The Marleyan economy is fine. Mostly fine." },
  // Fairy Tail Jewel — Wiki: 100 Jewels ≈ $1 (or 1 Yen ≈ 1 Jewel)
  { code:"JEWEL",name:"Jewel",             symbol:"J",  flag:"🌸",  category:"anime", usdRate:0.01,       realCurrency:false, universe:"Fairy Tail",                    canonical:false, flavorText:"Fairy Tail Guild is perpetually in debt because they destroy more property than any mission pays. Lucy's apartment is 70,000 Jewels/month ($700 USD). The Celestial Spirit King has no concept of money, which tracks." },
  // Demon Slayer Mon — historical Taisho era, Yen primary currency
  { code:"MON",  name:"Mon",               symbol:"文", flag:"🗡️",  category:"anime", usdRate:0.00065,    realCurrency:false, universe:"Demon Slayer",                  canonical:false, flavorText:"Tanjiro sold charcoal to feed his family before demons ended that career. Kinoe-level Slayer Corps salary is equivalent to ~$472,000 modern USD annually. The 'might die tonight' premium is substantial." },
  // One Punch Man — literally uses Japanese Yen
  { code:"OPYEN",name:"Yen (One Punch Man)",symbol:"¥", flag:"💪",  category:"anime", usdRate:0.0065,     realCurrency:false, universe:"One Punch Man",                 canonical:true,  flavorText:"Saitama, the most powerful being in the universe, clips supermarket coupons because his B-rank hero stipend barely covers rent. The economic commentary in One Punch Man is sharper than any of his punches. That's saying something." },
  // Bleach Kan — ~1 Yen per Kan (Seireitei Communication magazine same price as manga)
  { code:"KAN",  name:"Kan",               symbol:"環", flag:"⚔️",  category:"anime", usdRate:0.0065,     realCurrency:false, universe:"Bleach",                        canonical:false, flavorText:"Paid to Shinigami for protecting the living world. Ichigo has done this entire sacrifice for free. Zero Kan. The Soul Society has spent untold Kan rebuilding the gate Ichigo destroys every arc. Zero for the freelancer, millions for contractors." },
  // FMA:B Cens — ~$0.0065 (payphone 520 Cens ≈ ¥520 ≈ $3.38, slightly off but reasonable)
  { code:"CENS", name:"Cens",              symbol:"¢",  flag:"⚙️",  category:"anime", usdRate:0.0065,     realCurrency:false, universe:"Fullmetal Alchemist: Brotherhood",canonical:false,flavorText:"The currency of Amestris, a nation built on dark secrets and automail repair. The Elric brothers once traded their bodies to resurrect their mother. The exchange rate on that transaction was extremely unfavorable." },

  // ── MISC / CHAOS ────────────────────────────────────────────────────────────
  // Monopoly — ~$0.50 (Hasbro never set a rate; contextual pricing analysis)
  { code:"MNPLY",name:"Monopoly Money",    symbol:"M$", flag:"🎩",  category:"misc",  usdRate:0.50,       realCurrency:false, universe:"Monopoly",                      canonical:false, flavorText:"Hasbro never officially told us what M$ is worth, possibly because the entire point is to divorce players from the reality of money. Boardwalk costs $400 M$. Free Parking rewards you nothing. The banker always cheats. This is a children's game." },
  // Bitcoin substitute fun entries
  { code:"KARMA",name:"Internet Karma",   symbol:"⬆",  flag:"🌐",  category:"misc",  usdRate:0.0,        realCurrency:false, universe:"Reddit / The Internet",          canonical:false, flavorText:"Objectively worthless. People sacrifice hours of their lives for it anyway. Peak human behavior. Cannot be exchanged for anything. Has caused more arguments than most actual currencies." },
  { code:"CLOUT",name:"Clout",            symbol:"✨",  flag:"📱",  category:"misc",  usdRate:0.000001,   realCurrency:false, universe:"Social Media",                  canonical:false, flavorText:"Has replaced money in some circles. Can be exchanged for brand deals, parasocial relationships, or existential crisis. Volatile. Inflationary. Occasionally immaculate. Most often cursed." },
  { code:"VIBE", name:"Vibe",             symbol:"〰", flag:"😌",  category:"misc",  usdRate:0.000069,   realCurrency:false, universe:"The Internet (post-2019)",       canonical:false, flavorText:"The base unit of internet culture. Sometimes immaculate. Sometimes off. Never measured accurately. Vibe economics operates outside all known financial models. Alan Greenspan could not have predicted this." },
  { code:"DONUT",name:"Donut Buck",       symbol:"🍩", flag:"🏢",  category:"misc",  usdRate:1.50,       realCurrency:false, universe:"Corporate America",              canonical:false, flavorText:"The unofficial office economy. One glazed = performance review extension. One chocolate = raise discussion. The Donut Buck is the most universally understood currency in any workplace. HR is powerless against it." },
  { code:"KUDOS",name:"Kudos",            symbol:"👏", flag:"🎓",  category:"misc",  usdRate:0.001,      realCurrency:false, universe:"Academia / Corporate Life",      canonical:false, flavorText:"Given freely, accepted grudgingly. HR departments worldwide stake their careers on these. Studies show Kudos are inversely correlated with salary increases. This too is by design." },
  { code:"COCO", name:"Coconut",          symbol:"🥥", flag:"🏝️",  category:"misc",  usdRate:0.60,       realCurrency:false, universe:"Desert Island Economy",          canonical:false, flavorText:"The definitive post-shipwreck currency. More useful than gold (you can eat it), better than fiat (it's real and round), and the exchange rate floats (literally). The coconut standard: briefly discussed in monetary circles." },
  { code:"LEGO", name:"LEGO Stud",        symbol:"●",  flag:"🔴",  category:"misc",  usdRate:0.0005,     realCurrency:false, universe:"LEGO Universe",                  canonical:false, flavorText:"True value: the agony of stepping on one in the dark. GDP of LEGO City: immeasurable. LEGO is the world's largest tire manufacturer by unit count. This is a real fact. It is also irrelevant to this currency." },
  { code:"SPACE",name:"Space Credit",     symbol:"SC", flag:"🛸",  category:"misc",  usdRate:0.50,       realCurrency:false, universe:"Generic Sci-Fi Universe",        canonical:false, flavorText:"Every sci-fi show invents these. They are always called Credits. They are always slightly less valuable than a real dollar. Nobody in sci-fi has ever had a good pension plan." },
  { code:"CHOC", name:"Chocolate Bar",    symbol:"🍫", flag:"🏭",  category:"misc",  usdRate:1.49,       realCurrency:false, universe:"Universal",                     canonical:false, flavorText:"More stable than most emerging market currencies. Universally accepted. Melts in summer, causing predictable seasonal inflation. The Chocolate Standard was briefly proposed in 1971. It was not adopted." },
  { code:"SIMBL",name:"Schrödinger Buck", symbol:"?$", flag:"🐈",  category:"misc",  usdRate:0.5,        realCurrency:false, universe:"Quantum Economics",             canonical:false, flavorText:"Simultaneously worth $1 and $0 until observed. Collapsing the wave function by checking your balance is considered poor financial planning. Physicists refuse to open the wallet. Economists also refuse. For different reasons." },
];

// Quick picks for the homepage
const QUICK_PICKS = [
  { from:"USD", to:"GAL",   label:"$ → Galleons" },
  { from:"USD", to:"CAP",   label:"$ → Bottle Caps" },
  { from:"USD", to:"SEP",   label:"$ → Septims" },
  { from:"USD", to:"LATM",  label:"$ → Gold Latinum" },
  { from:"USD", to:"BELL",  label:"$ → Bells" },
  { from:"EUR", to:"CROW",  label:"€ → Witcher Crowns" },
  { from:"GBP", to:"GOLD",  label:"£ → WoW Gold" },
  { from:"CHF", to:"ZENI",  label:"Fr → Zeni" },
  { from:"USD", to:"MNPLY", label:"$ → Monopoly $" },
  { from:"USD", to:"RPGOLD",label:"$ → D&D Gold" },
  { from:"USD", to:"MGR",   label:"$ → Metro Rounds" },
  { from:"USD", to:"KARMA", label:"$ → Internet Karma" },
];
